apiVersion: apps/v1
kind: Deployment
metadata:
  name: segment-deployment
spec:
  selector:
    matchLabels:
      app: segments
  replicas: 2
  template:
    metadata:
      labels:
        app: segments
    spec:
      containers:
      - name: segments
        image: shaklotan/segments:version3
        ports:
          - name: segments
            containerPort: 80
        command:
        - /usr/bin/megaproj1
        - --period=15